### ISSUE TITLE
allow creation of service without a name

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/0-robot#33]
Currently the blueprint format always requires to use a name to identify a service.
Which mean service names need to be unique, so user can update them later on.
This is a heavy requirement and even more now that we can have multiple robots working together.

I want to propose a new format for blueprint that would remove this requirement of unique service name and still remains easy for user to write.

The idea is that a service is only uniquely identify by its guid. This guid is automatically generated by the 0-robot when creating the service. Having that in mind, it's not logical to ask a user to choose a service name.

To allow this from a blueprint perspective I propose to have 3 type of "blocks" in a blueprint.
- service create block
- service update block
- actions block

### Service create block
In this block the user list all the service he wants to create with their data.
example:
```yaml
template: github.com/jumpscale/0-robot/vm/0.0.1
name: vm1,
data:
  cpu: 1
  flist: https://hub.gig.tech/maxux/ubuntu-kubernetes.flist
  memory: 768
  nics:
  -   type: default
  node: '525400123451'
  port:
      2222: 22
```
As you can see there is still a `name` attribute in the creation block, but this name is only valid within this blueprint and not on the 0-robot themself.
This is required cause you need to be able to reference this new service in the `actions block`.

### Service update block:
This type of block is only used to update the data schema of an existing service. 
example:
```yaml
guid: 7f556a67-382c-4a19-94d0-483101d855dd
data:
  cpu: 2
```

As you see there is no name used here, we use the guid of the service since that's the only thing that can identify a service.

### Actions block
This block schedule actions on different services.
It can be new service created in the same blueprint, in which case they are identify using their name.
Or an existing service in which case we reference it using its guid.
example:
```yaml
actions:
  # for new service created in this blueprint
  - service: 'vm1'
    actions: install
   # for existing service
 - service: ' 7f556a67-382c-4a19-94d0-483101d855dd'
   actions: restart
```

Putting all this in one blueprint it would look like this:
```yaml
create:
  - template: github.com/jumpscale/0-robot/vm/0.0.1
    name: vm1
    data:
      cpu: 1
      flist: https://hub.gig.tech/maxux/ubuntu-kubernetes.flist
      memory: 768
      nics:
      -   type: default
      node: '525400123451'
      port:
          2222: 22

update:
  - guid: 7f556a67-382c-4a19-94d0-483101d855dd
    data:
     cpu: 2

actions:
  - service: vm1
    actions: install
  - service: 7f556a67-382c-4a19-94d0-483101d855dd
    actions: restart
```
