### ISSUE TITLE
Blueprint: actions fails to execute when multiple services exists with same name

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/0-robot#52]
Example
```yaml
services:
    - github.com/org/templates/user/0.0.1__azmy:
    - github.com/org/templates/account/0.0.1__azmy:

actions:
    service: 'azmy'
    actions: ['install']
```

This fails with exception 
`zerorobot.service_collection.TooManyResults: more then one results for service name=azmy, be more precise`

Even if we set the template to the exact template we want to schedule the action on, I still get the same error
