### ISSUE TITLE
Template: public data, or properties

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/0-robot#54]
Sometimes, a service need to be able to get some data from a service instance without be able to access it's data, like a read only property. 

I don't mind if this feature is going to be rejects, but then we have to find a way to fix the following scenario

## Scenario
- A `user` template defines a user object
- An `account` template defined an account object
- an `account` can authorise multiple users with certain permissions 
- the `account` needs the `user` ID to do so (not the username)
- only the `user` instance, knows about it's own ID

## Suggested solution

```python
class User(TemplateBase):
    @public
    @property
     def userID(self):
          return self.data['id']
```

In account
```python
def action(self):
    user = self.api.services.find(template_uid='.../user', name=username)[0]
    user_id = user.get('userID') 
    # or may be 
    user_id = user.userID # which is more pythonic
```

**Comment by zaibon** [comment]
By design it's not possible to read data from another service.
But what you can do is having an action that takes an argument.
So here, you could have a method on Account object that authorize a user and takes the user ID as argument.
So like that it's the service that holds the data and decide to share it, not an external service having access to the data of another one.

**Comment by muhamadazmy** [comment]
@zaibon this doesn't actually fix my problem, because the users `names` to authorise are actually defined on the account object.

As a (not complete) example below

```yaml
services:
   - github.com/org/templates/user/0.0.1__username1:
   - github.com/org/templates/user/0.0.1__username2:
   - github.com/org/templates/account/0.0.1__myaccount:
         users:
             - username1
             - username2
```

Now, while the user service holds all the user data (including his email and id)
the account on install, needs to authorise the `username1` , and `username2` users on itself. but it requires the actual user `ID` to do so (in our case `username1@itsyouonline`)

I am not sure exactly how your approach is going to fix that
